defaults: &DEFAULTS
  auth_server: <%= ENV['AUTH_SERVER'] %>
  sign_in_url: <%= ENV['SIGN_IN_URL'] %>
  root_url: <%= ENV['ROOT_URL'] %>
  client_id: <%= ENV['CLIENT_ID'] %>
  callback_url: <%= ENV['CALLBACK_URL'] %>
  client_app_permission: <%= ENV['CLIENT_APP_PERMISSION'] %>
  sso_username: <%= ENV['SSO_USERNAME'] %>
  sso_password: <%= ENV['SSO_PASSWORD'] %>

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
